#!/bin/bash

# zsh
bcomp config/macos/home/.zshrc ~/.zshrc

# git
bcomp config/shared/home/.gitconfig ~/.gitconfig

# starship
bcomp config/shared/home/.config/starship.toml ~/.config/starship.toml

# psql
bcomp config/unix/home/.psqlrc ~/.psqlrc

# ssh
bcomp config/unix/home/.ssh/config ~/.ssh/config

# hammerspoon
bcomp config/macos/home/.hammerspoon/init.lua ~/.hammerspoon/init.lua
