name: install

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  install:
    name: Install Tools
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: setup/macos
        run: |
          sh "${GITHUB_WORKSPACE}/setup/macos"
